Causal trees update
uber/causalml pull request #522
Opened 2022-06-24 00:28 UTC by alexander-pv

## Proposed changes

This PR is mainly about causal trees support.

* The architecture of a causal tree implementation was moved to a more modular approach:

1.  `BaseCausalDecisionTree` inherits everything is needed from scikit-learn `BaseDecisionTree` and modifies `fit()` method that stores only appropriate checks for causal trees.
2. `CausalTreeRegressor` now has `RegressorMixin` and `BaseCausalDecisionTree` parent classes which makes it fully compatible with scikit-learn.
3. Split criterion was moved to a separate `criterion.pyx` where `CausalRegressionCriterion` inherits methods from scikit-learn `RegressionCriterion` and implements `node_value()` to save the average of treatment effect for each node. `CausalMSE` now is a concrete class with impurity computations for causal trees. I also added `StandardMSE` concrete class which is actually standard MSE criterion from scikit-learn with modified `node_value()` method. So, now it is easy to add new criteria and see the influence of each criteria on a causal tree fit .

* Details about causal trees:

1. ATE bootstrap confidence intervals calculation in `CausalTreeRegressor`  now has multiprocessing support.
2. Now you can plot `CausalTreeRegressor` with standard scikit-learn function.
3. For a deeper research `CausalTreeRegressor` can calculate the number of treatment and control observations in each node, `_leaves_groups_cnt` low-level attribute.
4. `CausalRandomForestRegressor` based on scikit-learn with `CausalTreeRegressor` as `base_estimator`.
5. Method `calculate_error`  in `CausalRandomForestRegressor` calculates unbiased sampling variance. [Source](https://github.com/scikit-learn-contrib/forest-confidence-interval).
6. New Jupyter notebook `causal_trees_with_synthetic_data.ipynb` with `CausalTreeRegressor` and `CausalRandomForestRegressor` models.

* Tests:
1. Additional tests: `test_causal_trees.py`
2. `Makefile` contains install, build, test, clean. Now you can simply type `make test`. Cython code compilation is under the hood.
3. `setup()` function in `setup.py` now knows about `requirements-test.txt` dependencies thanks to `tests_require` parameter. No need to install them manually.

## Types of changes

What types of changes does your code introduce to **CausalML**?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/uber/causalml/blob/master/CONTRIBUTING.md) doc
- [x] I have signed the [CLA](https://cla-assistant.io/uber/causalml)
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged and published in downstream modules

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. This PR template is adopted from [appium](https://github.com/appium/appium).

2022-06-24 00:51 UTC, jeongyoonlee commented
Thanks @alexander-pv for your much needed contribution. We will review the PR soon.

2022-08-12 17:55 UTC, jeongyoonlee requested changes

2022-08-12 17:55 UTC, jeongyoonlee commented on causalml/inference/tree/causal/causaltree.py
> +from .base_tree import BaseCausalDecisionTree
`.base_tree` --> `._tree`

2022-08-12 17:55 UTC, jeongyoonlee commented on causalml/inference/tree/causal/causaltree.py
> +                if its impurity is above the threshold, otherwise it is a leaf.
Let's remove it as mentioned above.

2022-08-12 17:55 UTC, jeongyoonlee commented on causalml/inference/tree/causal/causaltree.py
> +        self.min_impurity_split = min_impurity_split
Same as above

2022-08-12 17:55 UTC, jeongyoonlee commented on causalml/inference/tree/causal/causaltree.py
> +            min_impurity_split=min_impurity_split,
same as above

2022-08-12 17:55 UTC, jeongyoonlee commented on causalml/inference/tree/causal/causaltree.py
> +            and self.min_impurity_split != float("-inf")
same as above

2022-08-12 17:55 UTC, jeongyoonlee commented on causalml/inference/tree/causal/causaltree.py
> +        min_impurity_split: float = float("-inf"),
same as above

2022-08-12 17:55 UTC, jeongyoonlee commented on causalml/inference/tree/causal/causaltree.py
> +                Threshold for early stopping in tree growth.
same as above

2022-08-12 17:55 UTC, jeongyoonlee commented on causalml/inference/tree/causal/causaltree.py
> +                "min_impurity_split",
same as above

2022-08-12 17:55 UTC, jeongyoonlee commented on causalml/inference/tree/causal/causaltree.py
> +        self.min_impurity_split = min_impurity_split
same as above

2022-08-12 17:55 UTC, jeongyoonlee commented on causalml/inference/tree/causal/_tree.py
> +                min_impurity_split,
Let's remove it

2022-08-12 17:55 UTC, jeongyoonlee commented on causalml/inference/tree/causal/_tree.py
> +                min_impurity_split,
Let's remove it

2022-08-12 17:55 UTC, jeongyoonlee commented on causalml/inference/tree/causal/_tree.py
> +            min_impurity_split = 0
Let's remove min_impurity_split to avoid errors with latest sklearn

2022-08-12 18:00 UTC, jeongyoonlee commented
Hi, @alexander-pv, 

Sorry for my late review. I thought that I left comments earlier but turned out that I didn't submit them and my review was somehow left pending. Code looks good and thanks for the sample notebook and test code which are very comprehensive. One ask is: let's remove `min_impurity_split` from the code so that we can use latest scikit-learn. Currently it raises "TypeError: __init__() got an unexpected keyword argument 'min_impurity_split'".

Thanks!

2022-08-13 20:52 UTC, alexander-pv commented
Hi, @jeongyoonlee ,

Thanks for the review, I pushed necessary changes.

I faced the thing that `min_impurity_split` removal in latest scikit-learn breaks tree building.  It turned out that new version of `DepthFirstTreeBuilder` prevent causal tree from growing new nodes.
See differences: [old condition](https://github.com/scikit-learn/scikit-learn/blob/2beed55847ee70d363bdbfe14ee4401438fba057/sklearn/tree/_tree.pyx#L221) vs [new condition](https://github.com/scikit-learn/scikit-learn/blob/baf828ca126bcb2c0ad813226963621cafe38adb/sklearn/tree/_tree.pyx#L216).
Since `EPSILON` constant in original cython file is widely used and can't be adjusted, I suggest to create `builder.pyx` with DepthFirstCausalTreeBuilder with necessary changes (see latest commits). This file can also be an example how to create custom tree builders via subclassing scikit-learn TreeBuilder.

2022-08-19 17:28 UTC, jeongyoonlee approved these changes
LGTM. Thanks again for your contribution. I really appreciate it!

2022-08-19 18:55 UTC, jeongyoonlee commented
Hi @alexander-pv, Py 3.7 test failed with the error as follows:
https://github.com/uber/causalml/runs/7923168250?check_suite_focus=true#step:6:492

Could you please check? If it's something that needs more time, we can merge this PR first and investigate it in a separate thread.

2022-08-21 00:30 UTC, alexander-pv commented
Hi, @jeongyoonlee, It seems that now everything is fixed :ok_hand:.

2022-08-21 00:47 UTC, merged

2022-08-21 00:47 UTC, jeongyoonlee commented
Merged! 👍🏻